codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "75...100"
  status:
    project:
      default:
        target: 80%
        threshold: 3%
    patch:
      default:
        target: 80%
        threshold: 3%