name: Publish Documentation

on:
  workflow_dispatch:

env:
  WYAM_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
  # secrets.GITHUB_TOKEN has no permissions to push, sadly.
  WYAM_DEPLOY_BRANCH: 'gh-pages'
  WYAM_DEPLOY_REMOTE: "${{ github.event.repository.html_url }}"

jobs:
  cake:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Fetch all tags and branches
      run: git fetch --prune --unshallow

    - name: Cache Tools
      uses: actions/cache@v3
      with:
        path: tools
        key: ${{ runner.os }}-doc-tools-${{ hashFiles('recipe.cake') }}

    - name: Publishing documentaiton
      uses: cake-build/cake-action@v1
      with:
        script-path: recipe.cake
        target: Force-Publish-Documentation
        verbosity: Diagnostic
        cake-version: 0.38.5
        cake-bootstrap: true
